apiVersion: v1.1
resources:
  - name: npmEnvExample
    type: declarativesystems/NpmEnv
    configuration:
      sourceArtifactory: artifactory # for resolving and publishing packages
      repositoryName: npm
  - name: gitPipelinesExampleNpmEnv
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/pipelines_example_npmenv
      branches:
        include: ^{{gitBranch}}$
      cancelPendingRunsOn:
        pullRequestUpdate: true
        newCommit: true

pipelines:
  - name: pipelinesExampleNpmEnv
    configuration:
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10
      runtime:
        type: image
        image:
          custom:
            name: declarativesystems.jfrog.io/docker-local/pipelines
            tag: 0.9.0
            registry: artifactory
            sourceRepository: docker-local
    steps:
      - name: yarnBuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: npmEnvExample
            - name: gitPipelinesExampleNpmEnv
        execution:
          onExecute:
            - cd ${res_gitPipelinesExampleNpmEnv_resourcePath}
            - make publish
