apiVersion: v1.1
resources:
  - name: npmEnvExample
    type: declarativesystems/NpmEnv
    configuration:
      sourceArtifactory: artifactory # for resolving and publishing packages
      repositoryName: npm
  - name: gitPipelinesExampleNpmEnv
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/pipelines_example_npmenv
pipelines:
  - name: pipelinesExampleNpmEnv
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: declarativesystems.jfrog.io/docker-local/pipelines
            tag: 0.7.0-27
            registry: artifactory
            sourceRepository: docker-local
    steps:
      - name: yarnBuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: npmEnvExample
            - name: gitPipelinesExampleNpmEnv
        execution:
          onExecute:
            - cd ${res_gitPipelinesExampleNpmEnv_resourcePath}
            - yarn build
            - yarn publish